### ISSUE TITLE
Implement the ASK/ANSWER routine

### ISSUE THREAD

**Issue by tradej** [tradej/devassistant-c2s#1]
Server can't ask client interactively for data.

**Comment by hroncok** [comment]
Server can do that. Don't know about the client.

**Comment by tradej** [comment]
Client now supports interactive querying, but doesn't hide passwords et al. when required (commit f7f7f9450460feeb7aaa89ef88f4cd3bfa249e48).

**Comment by hroncok** [comment]
It also just displays the prompt, not the message, etc.
