### ISSUE TITLE
Client should have a way to tell the server to shut down

### ISSUE THREAD

**Issue by hroncok** [tradej/devassistant-c2s#10]
Possibly:

```
{"query": {"request": "shutdown"}}
```

Server might or might not stop depending maybe depending on some arguments given to the server upon starting (e.g. `--user-stoppable`)

**Comment by tradej** [comment]
Server, 
![pls-stahp](https://cloud.githubusercontent.com/assets/1138123/10017553/b884b4b4-612f-11e5-901d-ae4a4fcb3af4.png)
