### ISSUE TITLE
Rewrite DevAssistant actions to use logger instead of print

### ISSUE THREAD

**Issue by tradej** [tradej/devassistant-c2s#17]
In many places, `print()` is used instead of `logger.info()`. This makes client/server communication of the output impossible.

**Comment by tradej** [comment]
While this is quite simple to implement in the original [DevAssistant](https://github.com/devassistant/devassistant) repository, I have hit one design obstacle—running e. g.

```
da pkg list --installed --simple
```

yields a result without any superficial text, which makes running commands like

```
da pkg install $(da pkg list --available --simple | grep python)
```

quite simple and easy to run. If we go with simply replacing all `print` calls to `logger.info()`, this functionality will be hindered, because all lines will be prepended with `INFO:`. I am thinking a keyword added to the API (like `clean_print` or something) could do the trick.

Comments?

**Comment by hroncok** [comment]
I think this is not such a big deal. If someone want's to grep the results, they just cut the INFO: out.

**Comment by hroncok** [comment]
OK, some code roughly committed and pushed to logger_info branch of devassistant.

The only remaining print statements are located in:
- `devassistant/cli/devassistant_argparse.py` - fine
- `devassistant/excepthook.py` - probably fine
- `devassistant/dapi/dapicli.py`:`uninstall_dap()` - related to #26
- `devassistant/actions.py`:`AutoCompleteAction` - fine
- `devassistant/actions.py`:`HelpAction` - fine
- `devassistant/command_helpers.py` - fine
- `setup.py` and `test/*` - fine

Test are passing, but no manual testing was yet done, so things may be broken.
