### ISSUE TITLE
Implement TCP client

### ISSUE THREAD

**Issue by tradej** [tradej/devassistant-c2s#18]

**Comment by hroncok** [comment]
Currently, arguments are processed after tree request. To be able to add --tcp / --unix argument similar to server, we might need to change that or have more argument parsers at the same time (is that even possible?)

**Comment by tradej** [comment]
Ad possible: I believe so - [`ArgumentParser.parse_known_args()`](https://docs.python.org/3/library/argparse.html?highlight=parse_known_args#argparse.ArgumentParser.parse_known_args)

**Comment by hroncok** [comment]
OK, when implemented, we should move the following to the first parser:
- [x] tcp/unix options
- [x] debug options
- [x] stop the server command

**Comment by tradej** [comment]
First two points fixed in 1ba4a528d582e050bdd619c575b4a2a6baf5959f

**Comment by hroncok** [comment]
For the record, --debug and --comm-debug are currently broken by 1ba4a52 (underscore notation disappeared, easy to fix, will do it).

**Comment by hroncok** [comment]
Ok, fixed back.

**Comment by hroncok** [comment]
I've juts pushed 3bb41b1 - now argparser is used for stop the server command as well, at least a bit. This way, it's the only way I found not to blow it up entirely.

I believe TCP server was implemented and all the side effects are fixed.

@tradej please look at my commit and see if it can be done any better, if you don't find a way, close this. thank you

**Comment by hroncok** [comment]
Is the TCP client finished and this could be closed?

**Comment by tradej** [comment]
Well, the implementation of stopping the server is a brutal hack, but it's working and I couldn't think of a nicer solution, so let's close it indeed. Thanks for it.
